[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f4ff"
textColor = "#262730"
font = "sans serif"

[client]
showSidebarNavigation = false
